// Mock data for the application
export const mockBooks = [
    {
      id: 1,
      title: "The Silent Patient",
      author: "Alex Michaelides",
      isbn: "978-1250301697",
      category: "Thriller",
      price: 24.99,
      stock: 45,
      status: "In Stock",
      image: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 2,
      title: "Where the Crawdads Sing",
      author: "Delia Owens",
      isbn: "978-0735219090",
      category: "Fiction",
      price: 22.99,
      stock: 32,
      status: "In Stock",
      image: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 3,
      title: "Atomic Habits",
      author: "James Clear",
      isbn: "978-0735211292",
      category: "Self-Help",
      price: 19.99,
      stock: 8,
      status: "Low Stock",
      image: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 4,
      title: "The Midnight Library",
      author: "Matt Haig",
      isbn: "978-0525559474",
      category: "Fiction",
      price: 21.99,
      stock: 0,
      status: "Out of Stock",
      image: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 5,
      title: "Project Hail Mary",
      author: "Andy Weir",
      isbn: "978-0593135204",
      category: "Sci-Fi",
      price: 26.99,
      stock: 18,
      status: "In Stock",
      image: "/placeholder.svg?height=40&width=40",
    },
  ]
  
  export const mockOrders = [
    {
      id: "ORD-7652",
      customer: "John Smith",
      email: "john.smith@example.com",
      date: "2023-05-12",
      total: 124.95,
      status: "Completed",
      items: 3,
    },
    {
      id: "ORD-7653",
      customer: "Sarah Johnson",
      email: "sarah.j@example.com",
      date: "2023-05-12",
      total: 89.99,
      status: "Processing",
      items: 2,
    },
    {
      id: "ORD-7654",
      customer: "Michael Brown",
      email: "m.brown@example.com",
      date: "2023-05-11",
      total: 54.5,
      status: "Shipped",
      items: 1,
    },
    {
      id: "ORD-7655",
      customer: "Emily Davis",
      email: "emily.d@example.com",
      date: "2023-05-10",
      total: 212.3,
      status: "Completed",
      items: 4,
    },
    {
      id: "ORD-7656",
      customer: "Robert Wilson",
      email: "r.wilson@example.com",
      date: "2023-05-09",
      total: 45.99,
      status: "Cancelled",
      items: 1,
    },
  ]
  
  export const mockUsers = [
    {
      id: 1,
      name: "John Smith",
      email: "john.smith@example.com",
      role: "Customer",
      status: "Active",
      joinDate: "2023-01-15",
      orders: 8,
      image: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 2,
      name: "Sarah Johnson",
      email: "sarah.j@example.com",
      role: "Admin",
      status: "Active",
      joinDate: "2022-11-03",
      orders: 0,
      image: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 3,
      name: "Michael Brown",
      email: "m.brown@example.com",
      role: "Customer",
      status: "Active",
      joinDate: "2023-02-22",
      orders: 3,
      image: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 4,
      name: "Emily Davis",
      email: "emily.d@example.com",
      role: "Editor",
      status: "Active",
      joinDate: "2022-09-18",
      orders: 0,
      image: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 5,
      name: "Robert Wilson",
      email: "r.wilson@example.com",
      role: "Customer",
      status: "Inactive",
      joinDate: "2023-03-05",
      orders: 1,
      image: "/placeholder.svg?height=40&width=40",
    },
  ]
  
  export const defaultSettings = {
    storeName: "Bookworm Haven",
    email: "contact@bookwormhaven.com",
    phone: "+1 (555) 123-4567",
    currency: "usd",
    address: "123 Bookstore Lane, Reading, CA 90210, United States",
    notifications: {
      newOrder: true,
      lowStock: true,
      customerAccount: false,
      marketing: true,
    },
  }
  